services:
  # api service
  api:
    image: hurtki/github-banners-api:${VER:?VER is required}
    platform: linux/amd64
    container_name: api
    restart: always
    env_file: ./api/.env
    environment:
      SERVICES_SECRET_KEY: "$SERVICES_SECRET_KEY"
      STORAGE_BASE_URL: "$STORAGE_BASE_URL"
    networks:
      - banners-net
      - api-net
      - kafka-net
    depends_on:
      kafka:
        condition: service_healthy
      api-psgr:
        condition: service_started
  # api service's Postgres database
  api-psgr:
    image: postgres:15
    env_file: ./api/.env
    container_name: api-psgr
    networks:
      - api-net
    volumes:
      - pgdata:/var/lib/postgresql/data
  # one instance of rendere service
  renderer:
    image: hurtki/github-banners-renderer:${VER:?VER is required}
    platform: linux/amd64
    env_file: ./renderer/.env
    container_name: renderer
    environment:
      SERVICES_SECRET_KEY: "${SERVICES_SECRET_KEY}"
      STORAGE_BASE_URL: "$STORAGE_BASE_URL"
    networks:
      - banners-net
      - kafka-net
    depends_on:
      kafka:
        condition: service_healthy
  # storage service
  storage:
    image: hurtki/github-banners-storage:${VER:?VER is required}
    platform: linux/amd64
    container_name: storage
    volumes:
      - banners-storage:/var/www/banners
    networks:
      - banners-net
  # nginx api gateway
  nginx:
    build:
      context: ./nginx/
      dockerfile: ./nginx/Dockerfile.prod
    container_name: nginx
    volumes:
      - banners-storage:/var/www/banners:ro
      # key + cert
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
    networks:
      - banners-net
    depends_on:
      - api
  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - kafka-data:/var/lib/kafka/data
volumes:
  pgdata:
    name: postgres_db_banners_api_ms
  kafka-data:
    name: kafka-data
  banners-storage:
    name: banners-storage
networks:
  api-net:
    driver: bridge
  banners-net:
    driver: bridge
  kafka-net:
    driver: bridge
