// Code generated by MockGen. DO NOT EDIT.
// Source: api/internal/domain/preview/usecase.go
//
// Generated by this command:
//
//	mockgen -source=api/internal/domain/preview/usecase.go -destination=api/internal/mocks/renderer-stats-service-mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/hurtki/github-banners/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsService) GetStats(arg0 context.Context, arg1 string) (domain.GithubUserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0, arg1)
	ret0, _ := ret[0].(domain.GithubUserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsServiceMockRecorder) GetStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsService)(nil).GetStats), arg0, arg1)
}

// MockPreviewRenderer is a mock of PreviewRenderer interface.
type MockPreviewRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewRendererMockRecorder
	isgomock struct{}
}

// MockPreviewRendererMockRecorder is the mock recorder for MockPreviewRenderer.
type MockPreviewRendererMockRecorder struct {
	mock *MockPreviewRenderer
}

// NewMockPreviewRenderer creates a new mock instance.
func NewMockPreviewRenderer(ctrl *gomock.Controller) *MockPreviewRenderer {
	mock := &MockPreviewRenderer{ctrl: ctrl}
	mock.recorder = &MockPreviewRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewRenderer) EXPECT() *MockPreviewRendererMockRecorder {
	return m.recorder
}

// RenderPreview mocks base method.
func (m *MockPreviewRenderer) RenderPreview(ctx context.Context, bannerInfo domain.BannerInfo) (*domain.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderPreview", ctx, bannerInfo)
	ret0, _ := ret[0].(*domain.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderPreview indicates an expected call of RenderPreview.
func (mr *MockPreviewRendererMockRecorder) RenderPreview(ctx, bannerInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderPreview", reflect.TypeOf((*MockPreviewRenderer)(nil).RenderPreview), ctx, bannerInfo)
}
