// Code generated by MockGen. DO NOT EDIT.
// Source: api/internal/domain/preview/service.go
//
// Generated by this command:
//
//	mockgen -source=api/internal/domain/preview/service.go -destination=api/internal/mocks/renderer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/hurtki/github-banners/api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPreviewRenderer is a mock of PreviewRenderer interface.
type MockPreviewRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewRendererMockRecorder
	isgomock struct{}
}

// MockPreviewRendererMockRecorder is the mock recorder for MockPreviewRenderer.
type MockPreviewRendererMockRecorder struct {
	mock *MockPreviewRenderer
}

// NewMockPreviewRenderer creates a new mock instance.
func NewMockPreviewRenderer(ctrl *gomock.Controller) *MockPreviewRenderer {
	mock := &MockPreviewRenderer{ctrl: ctrl}
	mock.recorder = &MockPreviewRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewRenderer) EXPECT() *MockPreviewRendererMockRecorder {
	return m.recorder
}

// RenderPreview mocks base method.
func (m *MockPreviewRenderer) RenderPreview(ctx context.Context, bannerInfo domain.BannerInfo) (*domain.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderPreview", ctx, bannerInfo)
	ret0, _ := ret[0].(*domain.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderPreview indicates an expected call of RenderPreview.
func (mr *MockPreviewRendererMockRecorder) RenderPreview(ctx, bannerInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderPreview", reflect.TypeOf((*MockPreviewRenderer)(nil).RenderPreview), ctx, bannerInfo)
}

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCache) Get(arg0 domain.BannerInfo) (*domain.Banner, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*domain.Banner)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), arg0)
}

// Set mocks base method.
func (m *MockCache) Set(arg0 string, arg1 *domain.Banner) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0, arg1)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), arg0, arg1)
}
