server {
    listen 80;

    root /var/www/;


    # --- API proxy ---
    location = /banners {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location ^~ /banners/preview {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # --- Static banners serving ---
    location ^~ /banners/ {
        try_files $uri.svg /banners/default;
    }
}
