# --- HTTPS thorugh Cloudflare Origin Certificate ---
server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    root /var/www/;

    # --- API proxy ---
    location = /banners {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location ^~ /banners/preview {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # --- Static banners serving ---
    location ^~ /banners/ {
        try_files $uri.svg /banners/default;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Last-Modified "";
        etag off;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        add_header Surrogate-Control "no-store" always;
    }
}
