on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  check-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git branch -r --contains $GITHUB_SHA | grep -q 'origin/master'
  api:
    runs-on: ubuntu-latest
    needs: check-master
    environment: dockerhub-push
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: hurtki
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          docker buildx build --push -t hurtki/github-banners-api:$VERSION ./api/
  renderer:
    runs-on: ubuntu-latest
    needs: check-master
    environment: dockerhub-push
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: hurtki
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          docker buildx build --push -t hurtki/github-banners-renderer:$VERSION ./renderer/
  storage:
    runs-on: ubuntu-latest
    needs: check-master
    environment: dockerhub-push
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: hurtki
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          docker buildx build --push -t hurtki/github-banners-storage:$VERSION ./storage/
  deploy:
    runs-on: ubuntu-latest
    needs: [api, renderer, storage]
    environment: ssh-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          envs: VERSION
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/github-banners/
            git checkout master
            git pull
            VER=$VERSION docker compose -f docker-compose.prod.yaml pull
            VER=$VERSION docker compose -f docker-compose.prod.yaml up -d --build
  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    environment: health-check
    steps:
      - name: http preview endpoint check
        run: |
          response=$(curl -si "https://${{ secrets.DOMAIN }}/banners/preview?username=hurtki&type=dark")
          echo "$response" | grep -q "^HTTP.*200" || { echo "❌ banner preview failed:"$'\n'"$response"; exit 1; }
  rollback:
    needs: health-check
    if: ${{ always() && needs.health-check.result == 'failure' }}
    runs-on: ubuntu-latest
    environment: ssh-deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get previous version
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' | sed 's/^v//')
          echo "PREV_VERSION=${PREV_TAG}" >> $GITHUB_ENV
      - name: Rollback via ssh
        uses: appleboy/ssh-action@v0.1.7
        env:
          VERSION: ${{ env.PREV_VERSION }}
        with:
          envs: PREV_VERSION
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/github-banners/
            VER=$PREV_VERSION docker compose -f docker-compose.prod.yaml pull
            VER=$PREV_VERSION docker compose -f docker-compose.prod.yaml up -d --build
